version: '2'
services:
  jenkins:
    build: jenkins
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkinshome:/var/jenkins_home/
  docker:
    image: docker:dind
    volumes:
      - jenkinsworkspace:/workspace/
    privileged: true
  jenkins-slave:
    build: jenkins-slave
    dns_search: [""]
    environment:
      - DOCKER_HOST=tcp://docker
    volumes:
      - jenkinsworkspace:/workspace/
    command:
      - -master
      - http://jenkins:8080
      - -name
      - test
      - -username
      - swarm
      - -password
      - swarm
volumes:
  jenkinshome: {}
  jenkinsworkspace: {}
