version: '2'
services:
  jenkins:
    build: jenkins
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HOST=tcp://docker
      - JENKINS_JAVA_OPTIONS="-Djenkins.install.runSetupWizard=false"
    networks:
      - jenkins
      - docker
    volumes:
      - jenkinshome:/var/jenkins_home/
    command:
      - --argumentsRealm.passwd.test=admin
      - --argumentsRealm.roles.test=admin
  docker:
    image: docker:dind
    volumes:
      - jenkinsworkspace:/workspace/
    privileged: true
    networks:
      - docker
  jenkins-slave:
    build: jenkins-slave
    environment:
      - DOCKER_HOST=tcp://docker
    networks:
      - jenkins
      - docker
    volumes:
      - jenkinsworkspace:/workspace/
    command:
      - -master
      - http://jenkins:8080
      - -name
      - test
      - -username
      - swarm
      - -password
      - swarm
volumes:
  jenkinshome: {}
  jenkinsworkspace: {}
networks:
  docker:
  jenkins:
